# Generated by Django 6.0.3 on 2026-03-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_department_alter_invitation_department_team'),
        ('users', '0004_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
