# Generated by Django 6.0.2 on 2026-05-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_delete_project'),
        ('tasks', '0004_alter_project_options_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='projects', to='organizations.department', verbose_name='Оролцогч хэлтсүүд'),
        ),
    ]
