# Generated by Django 6.0.2 on 2026-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Ирц', 'verbose_name_plural': 'Ирцүүд'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_on_time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Ирц өгсөн өргөрөг'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Ирц өгсөн уртраг'),
        ),
    ]
