# Generated by Django 6.0.2 on 2026-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_attendance_check_in_attendance_check_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in'], 'verbose_name': 'Ирц', 'verbose_name_plural': 'Ирцүүд'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ирсэн цаг'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Тарсан цаг'),
        ),
    ]
