# Generated by Django 6.0.2 on 2026-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_attendance_options_remove_attendance_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('IN', 'Ирсэн'), ('OUT', 'Тарсан')], default='IN', max_length=5, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Бүртгүүлсэн цаг'),
        ),
    ]
