# Generated by Django 6.0.2 on 2026-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
