# Generated by Django 6.0.2 on 2026-04-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_end_time_organization_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
